const names = [
  "Aarav Mehta",
  "Riya Sharma",
  "Kunal Patel",
  "Sneha Verma",
  "Dev Malhotra",
  "Priya Nair",
  "Arjun Desai",
  "Kavya Singh",
  "Yash Trivedi",
  "Ananya Kapoor",

  "Rahul Joshi",
  "Meera Shah",
  "Dhruv Bhatt",
  "Isha Gupta",
  "Nikhil Rao",
  "Tanvi Chawla",
  "Manav Soni",
  "Aditi ",
  "Harsh Vyas",
  "Pooja Iyer",

  "Rohan Das",
  "Simran Kaur",
  "Aditya Jain",
  "Neha Bansal",
  "Parth Thakkar",
  "Kriti Agrawal",
  "Tushar Yadav",
  "Naina Arora",
  "Ritesh Pandey",
  "Muskan Ali",

  "Sahil Choudhary",
  "Divya Menon",
  "Krish Solanki",
  "Payal Reddy",
  "Omkar Mishra",
  "Zoya Khan",
  "Vedant Goyal",
  "Alisha ",
  "Sarthak Dubey",
  "Bhavya Shetty",

  "Lakshya Arvind",
  "Shruti Pillai",
  "Mihir Gandhi",
  "Riddhi Parekh",
  "Kabir Anand",
  "Janvi Tiwari",
  "Ayush Rawat",
  "Tamanna ",
  "Chirag Modi",
  "Ishita Roy",
];

export function getRandomName() {
  return names[Math.floor(Math.random() * names.length)];
}

const messages = [
  "Data structures help organize data efficiently.",
  "Arrays store elements in contiguous memory locations.",
  "Linked lists use nodes connected by pointers.",
  "Stacks follow the Last In First Out principle.",
  "Queues follow the First In First Out principle.",
  "Trees are hierarchical data structures.",
  "Binary trees have at most two children.",
  "Graphs consist of vertices and edges.",
  "Hash maps provide fast data lookup.",
  "Time complexity measures algorithm efficiency.",

  "Space complexity measures memory usage.",
  "Big O notation describes worst-case performance.",
  "Recursion uses the call stack internally.",
  "Depth First Search explores deeply first.",
  "Breadth First Search explores level by level.",
  "Binary search works on sorted arrays.",
  "Sorting improves search performance.",
  "Heap is a special tree-based structure.",
  "Priority queue is implemented using heap.",
  "Trie is used for fast prefix searching.",

  "Dynamic programming solves overlapping subproblems.",
  "Greedy algorithms make local optimal choices.",
  "Two pointer technique reduces complexity.",
  "Sliding window improves array problems.",
  "Set stores unique values only.",
  "Map stores key value pairs.",
  "Adjacency list represents graphs efficiently.",
  "Adjacency matrix uses 2D arrays.",
  "Balanced trees improve search time.",
  "AVL tree maintains height balance.",

  "Red Black tree ensures logarithmic height.",
  "Hashing reduces search time complexity.",
  "Collision handling is important in hashing.",
  "Stack is used in undo operations.",
  "Queue is used in scheduling tasks.",
  "Deque allows insertion at both ends.",
  "Circular queue avoids memory wastage.",
  "Linked list allows dynamic memory allocation.",
  "Merge sort uses divide and conquer.",
  "Quick sort is efficient on average.",

  "Insertion sort works well for small data.",
  "Selection sort is simple but slow.",
  "Bubble sort repeatedly swaps elements.",
  "Graph traversal solves connectivity problems.",
  "Topological sort works on DAG.",
  "Union Find detects cycles in graph.",
  "Backtracking explores all possibilities.",
  "Memoization optimizes recursion.",
  "Bit manipulation improves performance.",
  "Data structures are the foundation of algorithms.",
];

export function getRandomMessage() {
  return messages[Math.floor(Math.random() * messages.length)];
}
